version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: arosaje_app
    container_name: arosapp-container
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: arosaje_api
    container_name: aroapi-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
 