version: '3.8'

services:
  api:
    build:
      context: ./API
    networks:
      - arosaje-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Le port public pour accéder à l'API via Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Montre le fichier de configuration nginx.conf
    depends_on:
      - api
    networks:
      - arosaje-network

  app:
    build:
      context: ./App
    ports:
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo Packager
      - "19002:19002"  # Expo Debugger
    networks:
      - arosaje-network

  api-tests:
    build:
      context: ./API
    command: ["npm", "test"]
    networks:
      - arosaje-network
    depends_on:
      - api

networks:
  arosaje-network:
    driver: bridge
