version: '3.8'

services:
  api:
    build:
      context: ./Arosaje/Api
    ports:
      - "3000:3000"
    networks:
      - arosaje-network

  app:
    build:
      context: ./Arosaje/App
    ports:
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo Packager
      - "19002:19002"  # Expo Debugger
    networks:
      - arosaje-network

  web:
    build:
      context: ./Arosaje/Web
    ports:
      - "80:80"
    networks:
      - arosaje-network

  api-tests:
    build:
      context: ./Arosaje/Api
    command: ["npm", "test"]
    networks:
      - arosaje-network
    depends_on:
      - api

networks:
  arosaje-network:
    driver: bridge
