name: APP CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: '18.x'

    steps:
      - name: ------------ RECUPERATION DU CODE DU REPO ------------
        uses: actions/checkout@v2

      - name: ------------ SET UP NODE JS SUR LES VERSION 18.x, 20.x ------------
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ------------ INSTALLATION DES DEPENDANCES (APP) ------------
        working-directory: App
        run: npm install

      - name: ------------ DEMARRAGE DU SERVEUR EXPO ------------
        working-directory: App
        run: |
          # Démarrer Expo en arrière-plan et capturer le PID
          nohup npx expo start > expo.log 2>&1 &
          echo $! > expo.pid
          sleep 10  # Attendre que le serveur démarre complètement

      - name: ------------ EXECUTION DES TESTS JEST (APP) ------------
        working-directory: App
        run: npm test

      - name: ------------ ARRÊTER LE SERVEUR EXPO ------------
        if: always()
        run: |
          # Lire le PID depuis le fichier et arrêter le serveur
          if [ -f App/expo.pid ]; then
            EXPO_PID=$(cat App/expo.pid)
            echo "Arrêt du serveur Expo avec PID $EXPO_PID"
            kill -9 $EXPO_PID || true
          else
            echo "Aucun PID trouvé pour le serveur Expo"
          fi
